CREATE TABLE USERS(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	NAME VARCHAR(100),
	SURNAME VARCHAR(100), 
	EMAIL VARCHAR(100), 
	PASSWORD VARCHAR(100)
);

CREATE PROC LOGIN(@NAME VARCHAR(100), @PASSWORD VARCHAR(100))
AS
BEGIN
	SELECT * FROM USERS WHERE NAME = @NAME AND PASSWORD = @PASSWORD;
END