DROP TABLE USERS;

CREATE TABLE USERS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	USERNAME VARCHAR(100),
	NAME VARCHAR(100),
	SURNAME VARCHAR(100), 
	EMAIL VARCHAR(100), 
	PASSWORD VARCHAR(100)
);

ALTER PROC LOGIN(@USERNAME VARCHAR(100), @PASSWORD VARCHAR(100))
AS
BEGIN
	SELECT * FROM USERS WHERE USERNAME = @USERNAME AND PASSWORD = @PASSWORD;
END